In [1]:
from flask import Flask, jsonify
from flask_cors import CORS
import pandas as pd
import numpy as np
from datetime import date
from sqlalchemy import create_engine

In [2]:
engine = create_engine('postgresql://postgres:root@localhost:5432/cocolevio')
query = 'SELECT * FROM "Cocoleviodata"'
df1 = pd.read_sql(query, engine)

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1832 entries, 0 to 1831
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Issue key          1832 non-null   object
 1   Issue id           1832 non-null   int64
 2   Issue Type         1832 non-null   object
 3   Project name       1832 non-null   object
 4   Project lead       1832 non-null   object
 5   Priority           1832 non-null   object
 6   Assignee           1768 non-null   object
 7   Reporter           1832 non-null   object
 8   Due date           1832 non-null   object
 9   Description        1248 non-null   object
 10  Original estimate  1777 non-null   float64
 11  Time Spent         1832 non-null   int64
 12  Status Category    1832 non-null   object
 13  Created            1832 non-null   object
 14  inward_problem     1832 non-null   int64
 15  outward_problem    1832 non-null   int64
dtypes: float64(1), int64(4), object(11)
memory usage: 229.1+ KB

In [4]:
df1['Status Category'].unique()

array(['To Do', 'Done', 'In Progress'], dtype=object)

df1[df1['Status Category']=='Done'].count()

In [5]:
df1.sample(10)

,Issue key,Issue id,Issue Type,Project name,Project lead,Priority,Assignee,Reporter,Due date,Description,Original estimate,Time Spent,Status Category,Created,inward_problem,outward_problem
1400,LEVI-939,19623,Task,Levi,Arun Kumar Saxena,P2,Shruti Chauhan,David Merrit,10-06-2025 00:00,We need to implement the â€œinitial benchmarking...,45732.504260,217260,In Progress,28-06-2025 00:00,0,0
1308,LEVI-533,19754,Task,Levi,Arun Kumar Saxena,P2,Tarun Bhati,Shivangi Mehra,27-06-2025 00:00,Two endpoints are being pushed by Rohit to Lev...,28800.000000,39600,Done,31-05-2025 00:00,0,1
904,LEVI-853,20308,Story,Levi,Arun Kumar Saxena,P3,None,Arun Kumar Saxena,29-06-2025 00:00,"Just a reminder, let it go to email\n\nSplit t...",86400.000000,0,To Do,18-06-2025 00:00,1,1
681,LEVI-1288,21286,Task,Levi,Arun Kumar Saxena,P2,Anand Kumar Chaudhary,Arun Kumar Saxena,08-06-2025 00:00,# Enforce MFA for user accounts to add an ext...,86400.000000,206100,In Progress,11-06-2025 00:00,0,0
1030,LEVI-747,20136,Task,Levi,Arun Kumar Saxena,P1,Saugata Chandra,Saugata Chandra,29-06-2025 00:00,None,46932.499468,55800,Done,30-05-2025 00:00,0,0
657,LEVI-1310,21485,Bug,Levi,Arun Kumar Saxena,P2,Tarun Bhati,Shivangi Mehra,20-06-2025 00:00,"\n\n!image-20240923-121730.png|width=1216,heig...",14400.000000,9900,Done,28-05-2025 00:00,0,0
1581,LEVI-294,18797,Test,Levi,Arun Kumar Saxena,P2,Shivangi Mehra,Shivangi Mehra,12-06-2025 00:00,User should be on settings module,NaN,0,To Do,11-06-2025 00:00,0,0
145,LEVI-1888,25362,Bug,Levi,Arun Kumar Saxena,P2,None,Shivangi Mehra,20-06-2025 00:00,"!image-20250305-115037.png|width=1065,height=5...",19922.437069,0,To Do,05-06-2025 00:00,0,0
738,LEVI-1225,20829,Task,Levi,Arun Kumar Saxena,P2,Dhirendra Pratap,Prateek Chaturvedi,06-06-2025 00:00,The labels in the main menu do not line up cor...,7200.000000,8100,Done,19-06-2025 00:00,0,0
735,LEVI-1228,20858,Task,Levi,Arun Kumar Saxena,P2,Dhirendra Pratap,Arun Kumar Saxena,19-06-2025 00:00,# Add Restrictions to limit no of applicant ac...,201600.000000,92700,Done,18-06-2025 00:00,0,1

In [6]:
df=df1[['Project name' , 'Status Category']]

In [7]:
len(df)

1832

In [8]:
cmplt=len(df[df['Status Category']=='Done'])/len(df)*100

In [9]:
cmplt

36.080786026200876

In [10]:
priority_order = {'P1': 1, 'P2': 2, 'P3': 3 , 'P4':4 , 'Blocker':0}

In [11]:
df1['priority_num'] = df1['Priority'].map(priority_order)

In [12]:
df1['Priority'].unique()

array(['P2', 'P1', 'P4', 'P3', 'Blocker'], dtype=object)

In [13]:
df_sorted = df1.sort_values(by=['outward_problem', 'priority_num'], ascending=[False, True])

In [14]:
df_sorted.head()

,Issue key,Issue id,Issue Type,Project name,Project lead,Priority,Assignee,Reporter,Due date,Description,Original estimate,Time Spent,Status Category,Created,inward_problem,outward_problem,priority_num
116,LEVI-1917,25905,Bug,Levi,Arun Kumar Saxena,Blocker,Anand Kumar Chaudhary,Arun Kumar Saxena,11-06-2025 00:00,"# After 2 failed attempts, unable to receive O...",14400.000000,21600,Done,17-06-2025 00:00,0,1,0
436,LEVI-1579,22957,Bug,Levi,Arun Kumar Saxena,Blocker,Rohit Bhimrao Jondhale,Arun Kumar Saxena,08-06-2025 00:00,"Hello Team,\n\nÂ \n\nToday our recruitment team...",17839.990688,4500,In Progress,15-06-2025 00:00,0,1,0
455,LEVI-1562,22940,Task,Levi,Arun Kumar Saxena,Blocker,Rohit Bhimrao Jondhale,Shruti Chauhan,13-06-2025 00:00,"# While creating the evaluation, I added 3 que...",43846.587207,60300,Done,26-06-2025 00:00,0,1,0
491,LEVI-1522,22838,Bug,Levi,Arun Kumar Saxena,Blocker,Rohit Bhimrao Jondhale,Saugata Chandra,13-06-2025 00:00,None,18204.567809,0,To Do,28-06-2025 00:00,0,1,0
493,LEVI-1520,22836,Task,Levi,Arun Kumar Saxena,Blocker,Anand Kumar Chaudhary,Anand Kumar Chaudhary,22-06-2025 00:00,None,47915.606020,18000,Done,29-06-2025 00:00,0,1,0

In [15]:
df1.columns

Index(['Issue key', 'Issue id', 'Issue Type', 'Project name', 'Project lead',
       'Priority', 'Assignee', 'Reporter', 'Due date', 'Description',
       'Original estimate', 'Time Spent', 'Status Category', 'Created',
       'inward_problem', 'outward_problem', 'priority_num'],
      dtype='object')